version: "3.8"
services:
  web:
    image: __ECR_IMAGE__
    environment:
      - ASPNETCORE_URLS=http://+:8080
    ports: ["80:8080"]
    networks: [webnet]
    deploy:
      replicas: 3
      placement:
        max_replicas_per_node: 1
        preferences:
          - spread: node.id

  viz:
    image: dockersamples/visualizer:stable
    deploy:
      placement:
        constraints: [node.role == manager]
    ports:
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks: [webnet]

networks:
  webnet:
    driver: overlay