AWSTemplateFormatVersion: '2010-09-09'
Description: Root stack for Docker Swarm (manager + 2 workers) using nested stacks

Parameters:
  StackNamePrefix:
    Type: String
    Default: swarm-cf
    Description: Prefix used for naming
  TemplateBucket:
    Type: String
    Description: S3 bucket that stores child templates (e.g. cf-artifacts-<acct>-<region>)
  TemplatePrefix:
    Type: String
    Default: swarm-iac/templates/
    Description: Key prefix inside the S3 bucket
  VpcId:
    Type: AWS::EC2::VPC::Id
    Description: VPC to deploy into (choose your default VPC)
  PublicSubnetId:
    Type: AWS::EC2::Subnet::Id
    Description: Public subnet for all three instances (default subnet is fine)
  AllowedSshCidr:
    Type: String
    Description: Your IP in CIDR for SSH (e.g. 1.2.3.4/32)
  KeyPairName:
    Type: AWS::EC2::KeyPair::KeyName
    Description: Existing EC2 key pair name
  InstanceType:
    Type: String
    Default: t3.small
  AmiId:
    Type: AWS::EC2::Image::Id
    Description: Amazon Linux 2023 AMI in this region
  TableName:
    Type: String
    Default: swarmcf-Submissions
  RepositoryName:
    Type: String
  GitHubOrg:
    Type: String
    Default: mymh13
  GitHubRepo:
    Type: String
    Default: scaleable_aws_turn-in-2
  GitHubRef:
    Type: String
    Default: refs/heads/main
  OidcThumbprint:
    Type: String
    Default: 6938fd4d98bab03faadb97b34396831e3780aea1

Resources:
  SwarmSecurityGroupStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub 'https://s3.${AWS::Region}.amazonaws.com/${TemplateBucket}/${TemplatePrefix}00-sg-swarm.yaml'
      Parameters:
        StackNamePrefix: !Ref StackNamePrefix
        VpcId: !Ref VpcId
        AllowedSshCidr: !Ref AllowedSshCidr

  IamEc2RoleStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub 'https://s3.${AWS::Region}.amazonaws.com/${TemplateBucket}/${TemplatePrefix}20-iam-ec2-role.yaml'
      Parameters:
        StackNamePrefix: !Ref StackNamePrefix
        TableName: !Ref TableName
        TemplateBucket:  !Ref TemplateBucket
        TemplatePrefix:  !Ref TemplatePrefix

  DynamoDbStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub 'https://s3.${AWS::Region}.amazonaws.com/${TemplateBucket}/${TemplatePrefix}30-dynamodb.yaml'
      Parameters:
        StackNamePrefix: !Ref StackNamePrefix
        TableName: !Ref TableName

  SwarmEc2Stack:
    Type: AWS::CloudFormation::Stack
    DependsOn: [ SwarmSecurityGroupStack, IamEc2RoleStack ]
    Properties:
      TemplateURL: !Sub 'https://s3.${AWS::Region}.amazonaws.com/${TemplateBucket}/${TemplatePrefix}10-ec2-swarm.yaml'
      Parameters:
        StackNamePrefix: !Ref StackNamePrefix
        PublicSubnetId: !Ref PublicSubnetId
        SecurityGroupId: !GetAtt SwarmSecurityGroupStack.Outputs.SwarmSecurityGroupId
        KeyPairName: !Ref KeyPairName
        InstanceType: !Ref InstanceType
        AmiId: !Ref AmiId
        InstanceProfileName: !GetAtt IamEc2RoleStack.Outputs.InstanceProfileName
        TemplateBucket:  !Ref TemplateBucket
        TemplatePrefix:  !Ref TemplatePrefix

  EcrStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub "https://${TemplateBucket}.s3.${AWS::Region}.amazonaws.com/${TemplatePrefix}25-ecr.yaml"
      Parameters:
        RepositoryName: !Ref RepositoryName
        ImageTagMutability: MUTABLE
        ScanOnPush: true
        KeepUntagged: 10

  OidcGitHubStack:
    Type: AWS::CloudFormation::Stack
    DependsOn: EcrStack   # optional; safe to include
    Properties:
      TemplateURL: !Sub 'https://s3.${AWS::Region}.amazonaws.com/${TemplateBucket}/${TemplatePrefix}26-github-oidc.yaml'
      Parameters:
        StackNamePrefix: !Ref StackNamePrefix
        RepositoryName:  !Ref RepositoryName
        GitHubOrg:       !Ref GitHubOrg
        GitHubRepo:      !Ref GitHubRepo
        GitHubRef:       !Ref GitHubRef
        OidcThumbprint:  !Ref OidcThumbprint

  LambdaProcessorStack:
    Type: AWS::CloudFormation::Stack
    DependsOn: DynamoDbStack
    Properties:
      TemplateURL: !Sub 'https://s3.${AWS::Region}.amazonaws.com/${TemplateBucket}/${TemplatePrefix}35-lambda-processor.yaml'
      Parameters:
        StackNamePrefix: !Ref StackNamePrefix
        TableName: !Ref TableName
        TableStreamArn: !GetAtt DynamoDbStack.Outputs.TableStreamArn

Outputs:
  ManagerPublicIp:
    Value: !GetAtt SwarmEc2Stack.Outputs.ManagerPublicIp
  SecurityGroupId:
    Value: !GetAtt SwarmSecurityGroupStack.Outputs.SwarmSecurityGroupId
  DynamoTableName:
    Value: !GetAtt DynamoDbStack.Outputs.TableName
  GitHubEcrPushRoleArn:
    Description: ARN of the IAM Role that GitHub Actions assumes via OIDC
    Value: !GetAtt OidcGitHubStack.Outputs.GitHubEcrPushRoleArn
    Export:
      Name: !Sub '${AWS::StackName}-GitHubEcrPushRoleArn'